[package]
name = "cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "argusctl"
path = "src/main.rs"

[dependencies]
agent = { path = "../agent" }
anyhow = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
system = { path = "../system" }
tokio = { workspace = true }
uuid = { workspace = true }
