/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'workspace-users': WorkspaceUserAuthOperations;
  };
  blocks: {};
  collections: {
    'workspace-users': WorkspaceUser;
    'project-spaces': ProjectSpace;
    'project-memberships': ProjectMembership;
    'data-models': DataModel;
    'data-records': DataRecord;
    'data-relations': DataRelation;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'workspace-users': WorkspaceUsersSelect<false> | WorkspaceUsersSelect<true>;
    'project-spaces': ProjectSpacesSelect<false> | ProjectSpacesSelect<true>;
    'project-memberships': ProjectMembershipsSelect<false> | ProjectMembershipsSelect<true>;
    'data-models': DataModelsSelect<false> | DataModelsSelect<true>;
    'data-records': DataRecordsSelect<false> | DataRecordsSelect<true>;
    'data-relations': DataRelationsSelect<false> | DataRelationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: WorkspaceUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface WorkspaceUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspace-users".
 */
export interface WorkspaceUser {
  id: string;
  displayName: string;
  /**
   * Argus organization UUID. This is the tenant boundary for content data.
   */
  organizationId: string;
  /**
   * Optional link to the Argus control-plane user UUID.
   */
  argusUserId?: string | null;
  role: 'admin' | 'member';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'workspace-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-spaces".
 */
export interface ProjectSpace {
  id: string;
  argusProjectId: string;
  /**
   * Argus organization UUID. Server-side project sync may stamp this with overrideAccess.
   */
  organizationId: string;
  name: string;
  /**
   * Optional client UUID/reference. Personal projects leave this empty.
   */
  clientId?: string | null;
  status: 'active' | 'paused' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-memberships".
 */
export interface ProjectMembership {
  id: string;
  organizationId: string;
  /**
   * Immutable after creation.
   */
  project: string | ProjectSpace;
  /**
   * Immutable after creation.
   */
  user: string | WorkspaceUser;
  role: 'manager' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-models".
 */
export interface DataModel {
  id: string;
  organizationId: string;
  argusProjectId: string;
  /**
   * Immutable after creation.
   */
  project: string | ProjectSpace;
  name: string;
  /**
   * Stable immutable API identifier inside the project, for example products or release_notes.
   */
  slug: string;
  description?: string | null;
  /**
   * Immutable after creation. Content models support drafts/publication and the public content API.
   */
  kind: 'data' | 'content';
  /**
   * Expose only published active records through the read-only public CMS API.
   */
  publicRead?: boolean | null;
  /**
   * Immutable content shape. Page records can contain blocks defined by component schemas.
   */
  contentRole: 'collection' | 'page' | 'component';
  allowedComponents?: (string | DataModel)[] | null;
  schemaVersion: number;
  status: 'active' | 'archived';
  fields: {
    key: string;
    label: string;
    type: 'text' | 'textarea' | 'number' | 'boolean' | 'date' | 'datetime' | 'json' | 'relationship';
    required?: boolean | null;
    hasMany?: boolean | null;
    targetModel?: (string | null) | DataModel;
    /**
     * Reserved typed settings such as min/max, enum values or UI hints.
     */
    settings?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Application data publishes immediately. Content models support Payload drafts and publication history.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-records".
 */
export interface DataRecord {
  id: string;
  organizationId: string;
  argusProjectId: string;
  /**
   * Immutable after creation.
   */
  project: string | ProjectSpace;
  /**
   * Immutable after creation.
   */
  model: string | DataModel;
  schemaVersion: number;
  /**
   * Scalar values validated against the selected model. Relationships are stored separately.
   */
  values:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Validated component blocks for page content. Empty for normal collection records.
   */
  layout:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Argus record lifecycle. Kept separate from Payload’s internal draft _status.
   */
  status: 'active' | 'archived';
  /**
   * Set when a content record is published for the first time after its latest draft state.
   */
  publishedAt?: string | null;
  createdBy?: (string | null) | WorkspaceUser;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Relationship endpoints are immutable. Delete and recreate an edge to change it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-relations".
 */
export interface DataRelation {
  id: string;
  organizationId: string;
  argusProjectId: string;
  project: string | ProjectSpace;
  sourceModel: string | DataModel;
  sourceRecord: string | DataRecord;
  fieldKey: string;
  targetModel: string | DataModel;
  targetRecord: string | DataRecord;
  updatedAt: string;
  createdAt: string;
}
/**
 * Project-owned images and optimized web variants.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  organizationId: string;
  argusProjectId: string;
  /**
   * Immutable project ownership.
   */
  project: string | ProjectSpace;
  alt: string;
  caption?: string | null;
  /**
   * Allow this file to be delivered anonymously and used by a published site.
   */
  publicRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'workspace-users';
        value: string | WorkspaceUser;
      } | null)
    | ({
        relationTo: 'project-spaces';
        value: string | ProjectSpace;
      } | null)
    | ({
        relationTo: 'project-memberships';
        value: string | ProjectMembership;
      } | null)
    | ({
        relationTo: 'data-models';
        value: string | DataModel;
      } | null)
    | ({
        relationTo: 'data-records';
        value: string | DataRecord;
      } | null)
    | ({
        relationTo: 'data-relations';
        value: string | DataRelation;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'workspace-users';
    value: string | WorkspaceUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'workspace-users';
    value: string | WorkspaceUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspace-users_select".
 */
export interface WorkspaceUsersSelect<T extends boolean = true> {
  displayName?: T;
  organizationId?: T;
  argusUserId?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-spaces_select".
 */
export interface ProjectSpacesSelect<T extends boolean = true> {
  argusProjectId?: T;
  organizationId?: T;
  name?: T;
  clientId?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-memberships_select".
 */
export interface ProjectMembershipsSelect<T extends boolean = true> {
  organizationId?: T;
  project?: T;
  user?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-models_select".
 */
export interface DataModelsSelect<T extends boolean = true> {
  organizationId?: T;
  argusProjectId?: T;
  project?: T;
  name?: T;
  slug?: T;
  description?: T;
  kind?: T;
  publicRead?: T;
  contentRole?: T;
  allowedComponents?: T;
  schemaVersion?: T;
  status?: T;
  fields?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        required?: T;
        hasMany?: T;
        targetModel?: T;
        settings?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-records_select".
 */
export interface DataRecordsSelect<T extends boolean = true> {
  organizationId?: T;
  argusProjectId?: T;
  project?: T;
  model?: T;
  schemaVersion?: T;
  values?: T;
  layout?: T;
  status?: T;
  publishedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-relations_select".
 */
export interface DataRelationsSelect<T extends boolean = true> {
  organizationId?: T;
  argusProjectId?: T;
  project?: T;
  sourceModel?: T;
  sourceRecord?: T;
  fieldKey?: T;
  targetModel?: T;
  targetRecord?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  organizationId?: T;
  argusProjectId?: T;
  project?: T;
  alt?: T;
  caption?: T;
  publicRead?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}