[package]
name = "control-api"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
common = { path = "../../crates/common" }
hex = { workspace = true }
protocol = { path = "../../crates/protocol", features = ["openapi"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tower-http = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
