[package]
name = "helper"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "helper"
path = "src/lib.rs"

[[bin]]
name = "argus-helper"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
protocol = { path = "../protocol" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
